import {
  TagShape,
  TagMaterial,
  PetType,
  TagBackground,
  TagOption,
} from '../types/pet-tag.types';

export const shapeImages: Record<TagShape, string> = {
  bone: '/assets/images/customize/molde-hueso.png',
  heart: '/assets/images/customize/molde-corazon.png',
  circle: '/assets/images/customize/molde-circular.png',
};

export const materialLabels: Record<TagMaterial, string> = {
  resin: 'Resina',
  aluminum: 'Aluminio',
};

export const petTypeLabels: Record<PetType, string> = {
  dog: 'Perro',
  cat: 'Gato',
  other: 'Otro',
};

export const sizeLabels = {
  small: 'Pequeño',
  medium: 'Mediano',
  large: 'Grande',
};

export const petSizes = {
  dog: ['small', 'medium', 'large'],
  cat: ['small', 'medium'],
  other: ['small', 'medium'],
};

// Datos de ejemplo para fondos
export const backgroundOptions: TagBackground[] = Array.from(
  { length: 21 },
  (_, i) => ({
    id: `bg${i}`,
    name: `Fondo ${i + 1}`,
    imageUrl: `/assets/images/customize/shapes/bg-${i}.png`,
    category: i >= 13 ? ('solid' as const) : ('pattern' as const),
  })
);

export const mockTags: TagOption[] = [
  {
    id: '1',
    shape: 'bone',
    material: 'resin',
    background: '/assets/images/customize/shapes/bg-1.png',
    name: 'Max',
    phone: '555-1234',
    imageUrl: '/assets/images/customize/shapes/bg-1.png',
    isCustomizable: true,
  },
  {
    id: '2',
    shape: 'heart',
    material: 'aluminum',
    background: '/assets/images/customize/shapes/bg-2.png',
    name: 'Luna',
    phone: '555-5678',
    imageUrl: '/assets/images/customize/shapes/bg-2.png',
    isCustomizable: true,
  },
  {
    id: '3',
    shape: 'circle',
    material: 'resin',
    background: '/assets/images/customize/shapes/bg-3.png',
    name: 'Buddy',
    phone: '555-9012',
    imageUrl: '/assets/images/customize/shapes/bg-3.png',
    isCustomizable: false,
  },
  {
    id: '4',
    shape: 'bone',
    material: 'aluminum',
    background: '/assets/images/customize/shapes/bg-4.png',
    name: 'Milo',
    phone: '555-3456',
    imageUrl: '/assets/images/customize/shapes/bg-4.png',
    isCustomizable: true,
  },
  {
    id: '5',
    shape: 'heart',
    material: 'resin',
    background: '/assets/images/customize/shapes/bg-5.png',
    name: 'Coco',
    phone: '8555-7890',
    imageUrl: '/assets/images/customize/shapes/bg-5.png',
    isCustomizable: false,
  },
  {
    id: '6',
    shape: 'circle',
    material: 'aluminum',
    background: '/assets/images/customize/shapes/bg-6.png',
    name: 'Nala',
    phone: '555-2345',
    imageUrl: '/assets/images/customize/shapes/bg-6.png',
    isCustomizable: true,
  },
  {
    id: '7',
    shape: 'bone',
    material: 'resin',
    background: '/assets/images/customize/shapes/bg-7.png',
    name: 'Rocky',
    phone: '555-6789',
    imageUrl: '/assets/images/customize/shapes/bg-7.png',
    isCustomizable: true,
  },
  {
    id: '8',
    shape: 'heart',
    material: 'aluminum',
    background: '/assets/images/customize/shapes/bg-8.png',
    name: 'Daisy',
    phone: '555-0123',
    imageUrl: '/assets/images/customize/shapes/bg-8.png',
    isCustomizable: false,
  },
  {
    id: '9',
    shape: 'circle',
    material: 'resin',
    background: '/assets/images/customize/shapes/bg-9.png',
    name: 'Charlie',
    phone: '555-4567',
    imageUrl: '/assets/images/customize/shapes/bg-9.png',
    isCustomizable: true,
  },
  {
    id: '10',
    shape: 'bone',
    material: 'aluminum',
    background: '/assets/images/customize/shapes/bg-10.png',
    name: 'Lola',
    phone: '555-8901',
    imageUrl: '/assets/images/customize/shapes/bg-10.png',
    isCustomizable: true,
  },
  {
    id: '11',
    shape: 'heart',
    material: 'resin',
    background: '/assets/images/customize/shapes/bg-11.png',
    name: 'Cooper',
    phone: '555-2345',
    imageUrl: '/assets/images/customize/shapes/bg-11.png',
    isCustomizable: false,
  },
  {
    id: '12',
    shape: 'circle',
    material: 'aluminum',
    background: '/assets/images/customize/shapes/bg-12.png',
    name: 'Bella',
    phone: '555-6789',
    imageUrl: '/assets/images/customize/shapes/bg-12.png',
    isCustomizable: true,
  },
  {
    id: '13',
    shape: 'bone',
    material: 'resin',
    background: '/assets/images/customize/shapes/bg-13.png',
    name: 'Lucy',
    phone: '555-0123',
    imageUrl: '/assets/images/customize/shapes/bg-13.png',
    isCustomizable: true,
  },
  {
    id: '14',
    shape: 'heart',
    material: 'aluminum',
    background: '/assets/images/customize/shapes/bg-14.png',
    name: 'Bailey',
    phone: '555-4567',
    imageUrl: '/assets/images/customize/shapes/bg-14.png',
    isCustomizable: false,
  },
  {
    id: '15',
    shape: 'circle',
    material: 'resin',
    background: '/assets/images/customize/shapes/bg-15.png',
    name: 'Molly',
    phone: '555-8901',
    imageUrl: '/assets/images/customize/shapes/bg-15.png',
    isCustomizable: true,
  },
  {
    id: '16',
    shape: 'bone',
    material: 'aluminum',
    background: '/assets/images/customize/shapes/bg-16.png',
    name: 'Rocky',
    phone: '555-2345',
    imageUrl: '/assets/images/customize/shapes/bg-16.png',
    isCustomizable: true,
  },
  {
    id: '17',
    shape: 'heart',
    material: 'resin',
    background: '/assets/images/customize/shapes/bg-17.png',
    name: 'Coco',
    phone: '555-6789',
    imageUrl: '/assets/images/customize/shapes/bg-17.png',
    isCustomizable: false,
  },
  {
    id: '18',
    shape: 'circle',
    material: 'aluminum',
    background: '/assets/images/customize/shapes/bg-18.png',
    name: 'Nala',
    phone: '555-0123',
    imageUrl: '/assets/images/customize/shapes/bg-18.png',
    isCustomizable: true,
  },
  {
    id: '19',
    shape: 'bone',
    material: 'resin',
    background: '/assets/images/customize/shapes/bg-19.png',
    name: 'Max',
    phone: '555-4567',
    imageUrl: '/assets/images/customize/shapes/bg-19.png',
    isCustomizable: true,
  },
  {
    id: '20',
    shape: 'heart',
    material: 'aluminum',
    background: '/assets/images/customize/shapes/bg-20.png',
    name: 'Luna',
    phone: '555-8901',
    imageUrl: '/assets/images/customize/shapes/bg-20.png',
    isCustomizable: false,
  },
  {
    id: '21',
    shape: 'bone',
    material: 'resin',
    background: '/assets/images/customize/shapes/bg-0.png',
    name: 'Max',
    phone: '555-1234',
    imageUrl: '/assets/images/customize/shapes/bg-0.png',
    isCustomizable: true,
  },
];
